=== yoanastefanova/XML_Project/vinyls.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT vinyls (vinyl+)>
    <!ELEMENT vinyl (artist, album, year, price, colour*, grams, inches, description?, condition?, copies, available)>
        <!ATTLIST vinyl id ID #REQUIRED
                    coloured  (Yes|No) #IMPLIED>              
        <!ELEMENT artist (band, style, hiatus?)>
            <!ATTLIST artist 
                        id ID #REQUIRED>
        <!ELEMENT album (name, genre, rating?, song+)>
            <!ATTLIST album 
                        length CDATA #REQUIRED>
            <!ELEMENT song (title)>  
                <!ATTLIST song 
                            duration CDATA #REQUIRED>

<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT grams (#PCDATA)>
<!ELEMENT inches (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT condition (#PCDATA)>   
<!ELEMENT copies (#PCDATA)>
<!ELEMENT available (#PCDATA)>
<!ELEMENT band (#PCDATA)>
<!ELEMENT style (#PCDATA)>
<!ELEMENT hiatus (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT title (#PCDATA)>

=== yoanastefanova/XML_Project/vinyls_4.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE vinyls SYSTEM "vinyls.dtd">
<?xml-stylesheet href="vinyls_html_4.xsl" type="text/xsl"?>


<vinyls>
    <vinyl id = "MVNGLTG" coloured = "Yes">
        <artist id = "MV">
            <band>Movements</band>
            <style>Емо</style>
        </artist>
        <album length = "43:57">
            <name>No Good Left to Give</name>
            <genre>Алтернативен Рок</genre>
            <song duration = "3:33">
                <title>In My Blood</title>
            </song>
            <song duration = "4:01">
                <title>Skin to Skin</title>
            </song>
            <song duration = "3:57">
                <title>Don't Give Up Your Ghost</title> 
            </song>
            <song duration = "4:01">
                <title>Tunnel Vision</title>
            </song>
            <song duration = "3:24">
                <title>Garden Eyes</title>
            </song>
            <song duration = "3:42">
                <title>12 Weeks</title>
            </song>
            <song duration = "4:07">
                <title>Living Apology</title>
            </song>
            <song duration = "4:13">
                <title>Santiago Peak</title>
            </song>
            <song duration = "3:10">
                <title>Seneca</title>
            </song>
            <song duration = "3:37">
                <title>Moonlight Lines</title>    
            </song>
            <song duration = "1:35">
                <title>No Good Left to Give</title>    
            </song>
            <song duration = "4:37">
                <title>Love Took the Last of It</title>    
            </song>
        </album>
        <year>2020</year>
        <price>65 лева</price>
        <colour>Розов</colour>
        <grams>190гр.</grams>
        <inches>12"</inches>
        <copies>3100 копия</copies>
        <available>В наличност</available>
    </vinyl>

    <vinyl id = "PUPTDIO" coloured = "Yes">
        <artist id = "PUP">
            <band>PUP</band>
            <style>Пънк Рок</style>
        </artist>
        <album length = "30:31">
            <name>No Good Left to Give</name>
            <genre>Пънк рок</genre>
            <song duration = "2:18">
                <title>If This Tour Doesn't Kill You, I Will</title>
            </song>
            <song duration = "2:28">
                <title>DVP</title>
            </song>
            <song duration = "3:00">
                <title>Doubts</title> 
            </song>
            <song duration = "3:21">
                <title>Sleep in the Heat</title>
            </song>
            <song duration = "3:53">
                <title>The Coast</title>
            </song>
            <song duration = "2:19">
                <title>Old Wounds</title>
            </song>
            <song duration = "2:26">
                <title>My Life Is Over and I Couldn't Be Happier</title>
            </song>
            <song duration = "3:07">
                <title>Can't Win</title>
            </song>
            <song duration = "3:39">
                <title>Familiar Patterns</title>
            </song>
            <song duration = "4:00">
                <title>Pine Point</title>    
            </song>
        </album>
        <year>2016</year>
        <price>40 лева</price>
        <colour>Бебешко Розово</colour>
        <grams>180гр.</grams>
        <inches>12"</inches>
        <copies>300 копия</copies>
        <available>В наличност</available>
    </vinyl>


    <vinyl id = "BMTHPH">
        <artist id = "BMTH">
            <band>Bring Me the Horizon</band>
            <style>Металкор</style>
        </artist>
        <album length = "32:10">
            <name>Post Human: Survival Horror</name>
            <genre>Металкор</genre>
            <song duration = "2:44">
                <title>Dear Diary</title>
            </song>
            <song duration = "4:51">
                <title>Parasite Eve</title>
            </song>
            <song duration = "3:35">
                <title>Teardrops</title> 
            </song>
            <song duration = "3:40">
                <title>Obey</title>
            </song>
            <song duration = "1:26">
                <title>Itch for the Cure </title>
            </song>
            <song duration = "3:38">
                <title>Kingslayer</title>
            </song>
            <song duration = "3:29">
                <title>1x1</title>
            </song>
            <song duration = "4:40">
                <title>Ludens</title>
            </song>
            <song duration = "4:03">
                <title>One Day the Only Butterflies Left Will Be in Your Chest as You March Towards Your Death</title>
            </song>
        </album>
        <year>2020</year>
        <price>35 лева</price>
        <colour>Черен</colour>
        <grams>180гр.</grams>
        <inches>12"</inches>
        <copies>3000 копия</copies>
        <available>В наличност</available>
    </vinyl>




</vinyls>

=== yoanastefanova/XML_Project/vinyls_3.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE vinyls SYSTEM "vinyls.dtd">
<?xml-stylesheet href="vinyls_html_3.xsl" type="text/xsl"?>


<vinyls>
    <vinyl id = "MKLUNA" coloured = "Yes">
        <artist id = "MATK">
            <band>Mat Kerekes</band>
            <style>Инди Рок</style>
        </artist>
        <album length = "36:43">
            <name> Luna &amp; the Wild Blue Everything</name>
            <genre>Инди Рок</genre>
            <song duration = "3:01">
                <title>The Clubs / The People's Attention</title>
            </song>
            <song duration = "2:50">
                <title>Direction</title>
            </song>
            <song duration = "3:41">
                <title>My Lucky #3</title> 
            </song>
            <song duration = "3:42">
                <title>In Every Inch, In Every Mile</title>
            </song>
            <song duration = "2:44">
                <title>Bosque Verde</title>
            </song>
            <song duration = "3:28">
                <title>Canvas</title>
            </song>
            <song duration = "4:35">
                <title>Riding In Your Car</title>
            </song>
            <song duration = "4:02">
                <title>From None</title>
            </song>
            <song duration = "4:39">
                <title>...For Anyone</title>
            </song>
            <song duration = "3:41">
                <title>The Means of ()</title>    
            </song>
        </album>
        <year>2016</year>
        <price>70 лева</price>
        <colour>Син</colour>
        <grams>180гр.</grams>
        <inches>12"</inches>
        <copies>700 копия</copies>
        <available>В наличност</available>
    </vinyl>


    <vinyl id = "MENZFE" coloured = "Yes">
        <artist id = "BT">
            <band>The Menzingers</band>
            <style>Пънк Рок</style>
        </artist>
        <album length = "45:55">
            <name>From Exile</name>
            <genre>Пънк Рок</genre>
            <song duration = "3:35">
                <title>America</title>
            </song>
            <song duration = "3:29">
                <title>Anna</title>
            </song>
            <song duration = "4:26">
                <title>High School Friend</title>
            </song>
            <song duration = "3:53">
                <title>Last to Know</title>
            </song>
            <song duration = "3:01">
                <title>Strangers Forever</title>
            </song>
            <song duration = "4:26">
                <title>Hello Exile</title>
            </song>
            <song duration = "2:44">
                <title>Portland</title>
            </song>
            <song duration = "4:04">
                <title>Strain Your Memory</title>
            </song>
            <song duration = "5:10">
                <title>I Can't Stop Drinking</title>
            </song>
            <song duration = "3:04">
                <title>Strawberry Mansion</title>
            </song>
            <song duration = "3:18">
               <title>London Drugs</title> 
            </song>
            <song duration = "4:37">
                <title>Farewell Youth</title> 
             </song>
        </album>
        <year>2019</year>
        <price>83 лева</price>
        <colour>Кафяв</colour>
        <grams>180гр.</grams>
        <inches>12"</inches>
        <copies>2300 копия</copies>
        <available>В наличност</available>
    </vinyl>


    <vinyl id = "NDADAI" coloured = "Yes">
        <artist id = "ND">
            <band>Neck Deep</band>
            <style>Поп Рок</style>
        </artist>
        <album length = "39:35">
            <name>All Distortions Are Intentional</name>
            <genre>Пънк Рок</genre>
            <song duration = "3:39">
                <title>Sonderland</title>
            </song>
            <song duration = "3:34">
                <title>Fall</title>
            </song>
            <song duration = "3:09">
                <title>Lowlife</title>
            </song>
            <song duration = "3:19">
                <title>Telling Stories</title>
            </song>
            <song duration = "3:09">
                <title>When You Know</title>
            </song>
            <song duration = "1:26">
                <title>Quarry</title>
            </song>
            <song duration = "3:47">
                <title>Sick Joke</title>
            </song>
            <song duration = "3:33">
                <title>What Took You So Long</title>
            </song>
            <song duration = "3:34">
                <title>Empty House</title>
            </song>
            <song duration = "3:04">
                <title>Little Dove</title>
            </song>
            <song duration = "3:38">
               <title>I Revolve (Around You)</title> 
            </song>
            <song duration = "3:43">
                <title>Pushing Daisies</title> 
             </song>
        </album>
        <year>2019</year>
        <price>50 лева</price>
        <colour>Оранжев</colour>
        <grams>180гр.</grams>
        <inches>12"</inches>
        <copies>3400 копия</copies>
        <available>В наличност</available>
    </vinyl>

</vinyls>

=== yoanastefanova/XML_Project/vinyls_5.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE vinyls SYSTEM "vinyls.dtd">
<?xml-stylesheet href="vinyls_xml_1.xsl" type="text/xsl"?>



<vinyls>
    <vinyl id = "FYSRDT" coloured = "Yes">
        <artist id = "FYS">
            <band>Four Year Strong</band>
            <style>Поп Пънк</style>
        </artist>
        <album length = "32:16">
            <name>No Good Left to Give</name>
            <genre>Мелодичен хардкор</genre>
            <song duration = "1:34">
                <title>The Take Over</title>
            </song>
            <song duration = "3:07">
                <title>Prepare to Be Digitally Manipulated</title>
            </song>
            <song duration = "3:33">
                <title>Abandon Ship or Abandon All Hope</title> 
            </song>
            <song duration = "3:36">
                <title>Heroes Get Remembered, Legends Never Die</title>
            </song>
            <song duration = "3:12">
                <title>Wrecked 'Em? Damn Near Killed 'Em</title>
            </song>
            <song duration = "2:37">
                <title>Catastrophe</title>
            </song>
            <song duration = "3:06">
                <title>Men Are from Mars, Women Are from Hell</title>
            </song>
            <song duration = "3:22">
                <title>Bada Bing! Wit' a Pipe!</title>
            </song>
            <song duration = "3:03">
                <title>Beatdown in the Key of Happy</title>
            </song>
            <song duration = "3:18">
                <title>If He's Here, Who's Runnin' Hell?</title>    
            </song>
            <song duration = "3:08">
                <title>Maniac (R.O.D.)</title>    
            </song>
        </album>
        <year>2019</year>
        <price>90 лева</price>
        <colour>Кристал/Лилаво</colour>
        <grams>190гр.</grams>
        <inches>12"</inches>
        <copies>1500 копия</copies>
        <available>В наличност</available>
    </vinyl>


    <vinyl id = "OWTSMG" coloured = "Yes">
        <artist id = "OASIS">
            <band>Oasis</band>
            <style>Рок</style>
        </artist>
        <album length = "50:00">
            <name>(What's the Story) Morning Glory?</name>
            <genre>Мелодичен хардкор</genre>
            <song duration = "3:21">
                <title>Hello</title>
            </song>
            <song duration = "3:59">
                <title>Roll With It</title>
            </song>
            <song duration = "4:18">
                <title>Wonderwall</title> 
            </song>
            <song duration = "4:48">
                <title>Don't Look Back In Anger</title>
            </song>
            <song duration = "5:41">
                <title>Hey Now!</title>
            </song>
            <song duration = "0:44">
                <title>The Swamp Song 1</title>
            </song>
            <song duration = "5:29">
                <title>Some Might Say</title>
            </song>
            <song duration = "4:51">
                <title>Cast No Shadow</title>
            </song>
            <song duration = "3:40">
                <title>She's Electric</title>
            </song>
            <song duration = "5:03">
                <title>Morning Glory</title>    
            </song>
            <song duration = "0:39">
                <title>The Swamp Song 2</title>    
            </song>
            <song duration = "7:27">
                <title>Champagne Supernova</title>    
            </song>
        </album>
        <year>1995</year>
        <price>57 лева</price>
        <colour>Сребърен</colour>
        <grams>190гр.</grams>
        <inches>12"</inches>
        <copies>1500 копия</copies>
        <available>Не е наличност</available>
    </vinyl>


    <vinyl id = "RTJ4" coloured = "Yes">
        <artist id = "RTJ">
            <band>Run The Jewels</band>
            <style>Хип Хоп</style>
        </artist>
        <album length = "38:57">
            <name>RTJ4</name>
            <genre>Хип Хоп</genre>
            <song duration = "2:26">
                <title>Yankee and the Bravе</title>
            </song>
            <song duration = "3:01">
                <title>Ooh La La</title>
            </song>
            <song duration = "3:21">
                <title>Out of Sight</title> 
            </song>
            <song duration = "3:58">
                <title>Holy Calamafuck</title>
            </song>
            <song duration = "3:03">
                <title>Goonies vs. E.T.</title>
            </song>
            <song duration = "3:55">
                <title>Walking in the Snow</title>
            </song>
            <song duration = "3:25">
                <title>Just</title>
            </song>
            <song duration = "2:57">
                <title>Never Look Back</title>
            </song>
            <song duration = "2:32">
                <title>The Ground Below</title>
            </song>
            <song duration = "3:37">
                <title>Pulling the Pin</title>    
            </song>
            <song duration = "6:42">
                <title>A Few Words for the Firing Squad</title>    
            </song>
        </album>
        <year>2020</year>
        <price>120 лева</price>
        <colour>Маджента/Златен</colour>
        <grams>190гр.</grams>
        <inches>12"</inches>
        <copies>1500 копия</copies>
        <available>Не е наличност</available>
    </vinyl>


</vinyls>

=== yoanastefanova/XML_Project/vinyls_2.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE vinyls SYSTEM "vinyls.dtd">
<?xml-stylesheet href="vinyls_html_2.xsl" type="text/xsl"?>


<vinyls>
    <vinyl id = "BTST3" coloured = "Yes">
        <artist id = "BT">
            <band>Billy Talent</band>
            <style>Алтернативен Рок</style>
        </artist>
        <album length = "43:30">
            <name>Billy Talent 3</name>
            <genre>Пост-пънк</genre>
            <song duration = "3:49">
                <title>Devil on My Shoulder</title>
            </song>
            <song duration = "4:13">
                <title>Rusted from the Rain</title>
            </song>
            <song duration = "4:09">
                <title>Saint Veronica</title>
            </song>
            <song duration = "4:12">
                <title>Tears Into Wine</title>
            </song>
            <song duration = "3:14">
                <title>White Sparrows</title>
            </song>
            <song duration = "3:21">
                <title>Pocketful of Dreams</title>
            </song>
            <song duration = "4:27">
                <title>The Dead Can't testify</title>
            </song>
            <song duration = "4:30">
                <title>Diamond on a Landmine</title>
            </song>
            <song duration = "3:22">
                <title>Turn Your Back</title>
            </song>
            <song duration = "3:39">
                <title>Sudden Movements</title>
            </song>
            <song duration = "4:03">
               <title>Definition of Destiny</title> 
            </song>
        </album>
        <year>2009</year>
        <price>79 лева</price>
        <colour>Зелен</colour>
        <grams>190гр.</grams>
        <inches>12"</inches>
        <description>Издаден на 10 юли 2009 година, албумът дебютира като номер едно в Канада.</description>
        <copies>2300 копия</copies>
        <available>В наличност</available>
    </vinyl>


    <vinyl id = "INCSCIENCE" coloured = "Yes">
        <artist id = "INC">
            <band>Incubus</band>
            <style>Алтернативен Рок</style>
        </artist>
        <album length = "55:52">
            <name>S.C.I.E.N.C.E</name>
            <genre>Ню Метал</genre>
            <song duration = "3:22">
                <title>Redefine</title>
            </song>
            <song duration = "3:13">
                <title>Vitamin</title>
            </song>
            <song duration = "3:51">
                <title>New Skin</title>
            </song>
            <song duration = "4:07">
                <title>Idiot Box</title>
            </song>
            <song duration = "3:37">
                <title>Glass</title>
            </song>
            <song duration = "3:03">
                <title>Magic Medicine</title>
            </song>
            <song duration = "3:11">
                <title>A Certain Shade of Green</title>
            </song>
            <song duration = "3:11">
                <title>Favorite Things</title>
            </song>
            <song duration = "4:26">
                <title>Summer Romance</title>
            </song>
            <song duration = "3:50">
                <title>Nebula</title>
            </song>
            <song duration = "3:55">
               <title>Deep Inside</title> 
            </song>
            <song duration = "16:05">
                <title>Calgone</title>
            </song>
        </album>
        <year>1997</year>
        <price>90 лева</price>
        <colour>Трансперантно Синьо</colour>
        <grams>180гр.</grams>
        <inches>12"</inches>
        <description>Това е вторият албум на групата. В него има влияние на джаз, фънк, хип-хоп и техно.</description>
        <copies>2000 копия</copies>
        <available>Не е в наличност</available>
    </vinyl>



    <vinyl id = "YMASSP">
        <artist id = "YMAS">
            <band>You Me At Six</band>
            <style>Алтернативен Рок</style>
        </artist>
        <album length = "55:52">
            <name>SUCKAPUNCH</name>
            <genre>Рок</genre>
            <song duration = "4:27">
                <title>Nice to Me</title>
            </song>
            <song duration = "2:08">
                <title>Make Me Feel Alive</title>
            </song>
            <song duration = "3:45">
                <title>Beautiful Way</title>
            </song>
            <song duration = "3:29">
                <title>WYDRN</title>
            </song>
            <song duration = "4:59">
                <title>Suckapunch</title>
            </song>
            <song duration = "3:08">
                <title>KIll the Mood</title>
            </song>
            <song duration = "5:39">
                <title>Glasgow</title>
            </song>
            <song duration = "3:30">
                <title>Adrenaline</title>
            </song>
            <song duration = "4:01">
                <title>Voicenotes</title>
            </song>
            <song duration = "4:28">
               <title>Finish What I Started</title> 
            </song>
            <song duration = "3:27">
                <title>What's It Like</title>
            </song>
        </album>
        <year>2021</year>
        <price>55 лева</price>
        <colour>Черен</colour>
        <grams>180гр.</grams>
        <inches>12"</inches>
        <description>Издаден на 15 януари 2021 година, това е седмият албум на групата.</description>
        <copies>4000 копия</copies>
        <available>В наличност</available>
    </vinyl>









    
</vinyls>
